version: "3.0"
services:
  milesight-decoder:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "Milesight Decoder"
      MODULE_TYPE: "Processing"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      LABEL: ''
    ports:
      - 80:80